In [1]:
import numpy as np
a=np.array([[1,2,3,4],
            [8,2,3,4]])
b=np.min(a , axis = 0)
print(a)
print(b)

[[1 2 3 4]
 [8 2 3 4]]
[1 2 3 4]


In [2]:
import numpy as np
a=np.array([[1,2,3,4],
            [8,2,3,4]])
b=np.min(a , axis = 0)
print(a)
print(b)

[[1 2 3 4]
 [8 2 3 4]]
[1 2 3 4]
