In [33]:
import pandas as pd

In [34]:
import numpy as np

In [35]:
arr = np.array([[1,6012],[2,7079],[3,6886],[4,7230],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9569]])

In [36]:
arr

array([[   1, 6012],
       [   2, 7079],
       [   3, 6886],
       [   4, 7230],
       [   5, 4598],
       [   6, 5564],
       [   7, 6971],
       [   8, 7763],
       [   9, 8032],
       [  10, 9569]])

In [66]:
c = arr+[0,2000]
c

array([[    1,  8012],
       [    2,  9079],
       [    3,  8886],
       [    4,  9230],
       [    5,  6598],
       [    6,  7564],
       [    7,  8971],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

In [72]:
for i in l[:,1]:
    if i > 9000:
        print(i)

9079
9230
9763
10032
11569


In [62]:
np.sort(l[:,1])

array([ 6598,  7564,  8012,  8886,  8971,  9079,  9230,  9763, 10032,
       11569])

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
series = pd.Series([78,92,36,64,89])

In [4]:
series

0    78
1    92
2    36
3    64
4    89
dtype: int64

In [6]:
series.values

array([78, 92, 36, 64, 89], dtype=int64)

In [7]:
series.index

RangeIndex(start=0, stop=5, step=1)