In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("dataset/titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1       0.0       3   
1            2       NaN       1   
2            3       NaN       3   
3            4       NaN       1   
4            5       0.0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282      NaN   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     887 non-null    float64
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          713 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         888 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(3), int64(4), object(5)
memory usage: 83.7+ KB


In [4]:
df.isnull().sum()

PassengerId      0
Survived         4
Pclass           0
Name             0
Sex              0
Age            178
SibSp            0
Parch            0
Ticket           0
Fare             3
Cabin          687
Embarked         2
dtype: int64

In [5]:
df.drop(["PassengerId","Name","Ticket","Cabin"],axis = 1,inplace=True)

In [6]:
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0.0       3    male  22.0      1      0   7.2500        S
1         NaN       1  female  38.0      1      0  71.2833        C
2         NaN       3  female   NaN      0      0      NaN        S
3         NaN       1  female  35.0      1      0  53.1000        S
4         0.0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886       0.0       2    male  27.0      0      0  13.0000        S
887       1.0       1  female  19.0      0      0  30.0000        S
888       0.0       3  female   NaN      1      2  23.4500        S
889       1.0       1    male  26.0      0      0  30.0000        C
890       0.0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [7]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

In [8]:
x = df.drop(columns = ["Survived"])
x

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         3    male  22.0      1      0   7.2500        S
1         1  female  38.0      1      0  71.2833        C
2         3  female   NaN      0      0      NaN        S
3         1  female  35.0      1      0  53.1000        S
4         3    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
886       2    male  27.0      0      0  13.0000        S
887       1  female  19.0      0      0  30.0000        S
888       3  female   NaN      1      2  23.4500        S
889       1    male  26.0      0      0  30.0000        C
890       3    male  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

In [9]:
y = df[["Survived"]]
y

Survived
0         0.0
1         NaN
2         NaN
3         NaN
4         0.0
..        ...
886       0.0
887       1.0
888       0.0
889       1.0
890       0.0

[891 rows x 1 columns]

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y , test_size = 0.2,train_size = 0.8)

In [11]:
x_train

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
136       1  female  19.0      0      2  26.2833        S
662       1    male  47.0      0      0  25.5875        S
509       3    male  26.0      0      0  56.4958        S
805       3    male  31.0      0      0   7.7750        S
637       2    male  31.0      1      1  26.2500        S
..      ...     ...   ...    ...    ...      ...      ...
455       3    male  29.0      0      0   7.8958        C
704       3    male  26.0      1      0   7.8542        S
427       2  female  19.0      0      0  26.0000        S
13        3    male  39.0      1      5  31.2750        S
774       2  female  54.0      1      3  23.0000        S

[712 rows x 7 columns]

In [12]:
x_test

Pclass     Sex   Age  SibSp  Parch    Fare Embarked
460       1    male  48.0      0      0  26.550        S
110       1    male  47.0      0      0  52.000        S
510       3    male  29.0      0      0   7.750        Q
792       3  female   NaN      8      2  69.550        S
636       3    male  32.0      0      0   7.925        S
..      ...     ...   ...    ...    ...     ...      ...
129       3    male  45.0      0      0   6.975        S
407       2    male   3.0      1      1  18.750        S
259       2  female  50.0      0      1  26.000        S
243       3    male  22.0      0      0   7.125        S
837       3    male   NaN      0      0   8.050        S

[179 rows x 7 columns]

In [13]:
y_train

Survived
136       1.0
662       0.0
509       1.0
805       0.0
637       0.0
..        ...
455       1.0
704       0.0
427       1.0
13        0.0
774       1.0

[712 rows x 1 columns]

In [14]:
y_test

Survived
460       1.0
110       0.0
510       1.0
792       0.0
636       0.0
..        ...
129       0.0
407       1.0
259       1.0
243       0.0
837       0.0

[179 rows x 1 columns]

In [15]:
df.isnull().sum()

Survived      4
Pclass        0
Sex           0
Age         178
SibSp         0
Parch         0
Fare          3
Embarked      2
dtype: int64

In [16]:
df.dropna(subset = ["Survived","Fare","Embarked"],inplace = True)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 883 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  883 non-null    float64
 1   Pclass    883 non-null    int64  
 2   Sex       883 non-null    object 
 3   Age       708 non-null    float64
 4   SibSp     883 non-null    int64  
 5   Parch     883 non-null    int64  
 6   Fare      883 non-null    float64
 7   Embarked  883 non-null    object 
dtypes: float64(3), int64(3), object(2)
memory usage: 62.1+ KB


In [18]:
df.sample()

Survived  Pclass     Sex   Age  SibSp  Parch   Fare Embarked
816       0.0       3  female  23.0      0      0  7.925        S

In [19]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [20]:
tr = ColumnTransformer(transformers = [
    ('t1',SimpleImputer(),["Age"]),
    ('t2',OneHotEncoder(drop = "first",sparse=False),["Sex","Embarked"])
],remainder = "passthrough")

In [21]:
tr

ColumnTransformer(remainder='passthrough',
                  transformers=[('t1', SimpleImputer(), ['Age']),
                                ('t2',
                                 OneHotEncoder(drop='first', sparse=False),
                                 ['Sex', 'Embarked'])])

In [22]:
df_t = tr.fit_transform(df)
df_t

array([[22.        ,  1.        ,  0.        , ...,  1.        ,
         0.        ,  7.25      ],
       [35.        ,  1.        ,  0.        , ...,  0.        ,
         0.        ,  8.05      ],
       [29.65278249,  1.        ,  1.        , ...,  0.        ,
         0.        ,  8.4583    ],
       ...,
       [29.65278249,  0.        ,  0.        , ...,  1.        ,
         2.        , 23.45      ],
       [26.        ,  1.        ,  0.        , ...,  0.        ,
         0.        , 30.        ],
       [32.        ,  1.        ,  1.        , ...,  0.        ,
         0.        ,  7.75      ]])

In [23]:
df_t.shape

(883, 9)

In [24]:
tr.fit_transform(x_train)

array([[19.    ,  0.    ,  0.    , ...,  0.    ,  2.    , 26.2833],
       [47.    ,  1.    ,  0.    , ...,  0.    ,  0.    , 25.5875],
       [26.    ,  1.    ,  0.    , ...,  0.    ,  0.    , 56.4958],
       ...,
       [19.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 26.    ],
       [39.    ,  1.    ,  0.    , ...,  1.    ,  5.    , 31.275 ],
       [54.    ,  0.    ,  0.    , ...,  1.    ,  3.    , 23.    ]])

In [25]:
tr.fit_transform(x_test)

array([[48.        ,  1.        ,  0.        , ...,  0.        ,
         0.        , 26.55      ],
       [47.        ,  1.        ,  0.        , ...,  0.        ,
         0.        , 52.        ],
       [29.        ,  1.        ,  1.        , ...,  0.        ,
         0.        ,  7.75      ],
       ...,
       [50.        ,  0.        ,  0.        , ...,  0.        ,
         1.        , 26.        ],
       [22.        ,  1.        ,  0.        , ...,  0.        ,
         0.        ,  7.125     ],
       [30.34340426,  1.        ,  0.        , ...,  0.        ,
         0.        ,  8.05      ]])