In [32]:
import pandas as pd
import numpy as np

In [33]:
df = pd.read_csv("dataset/Housing.csv")

In [34]:
df.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


In [36]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [37]:
x = pd.DataFrame(df)

In [38]:
x.drop(columns = ["price"],inplace = True)

In [39]:
x["furnishingstatus"].unique()

array(['furnished', 'semi-furnished', 'unfurnished'], dtype=object)

In [40]:
y = pd.DataFrame(df["price"])

In [41]:
y

price
0    13300000
1    12250000
2    12250000
3    12215000
4    11410000
..        ...
540   1820000
541   1767150
542   1750000
543   1750000
544   1750000

[545 rows x 1 columns]

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
x_train,x_test,y_train,y_test = train_test_split(x,y , test_size = 0.2,train_size = 0.8)

In [44]:
x_train

area  bedrooms  bathrooms  stories mainroad guestroom basement  \
209  6720         3          1        1      yes        no       no   
362  4050         2          1        1      yes        no       no   
112  4300         6          2        2      yes        no       no   
352  5830         2          1        1      yes        no       no   
348  3150         2          2        1       no        no      yes   
..    ...       ...        ...      ...      ...       ...      ...   
420  4120         2          1        2      yes        no       no   
282  2175         3          1        2       no       yes      yes   
55   6000         3          1        2      yes        no       no   
456  2398         3          1        1      yes        no       no   
200  4520         3          1        2      yes        no      yes   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
209              no              no        0       no      unfurnished  
362              no              no        0       no        furnished  
112              no              no        0       no        furnished  
352              no              no        2       no      unfurnished  
348              no              no        0       no   semi-furnished  
..              ...             ...      ...      ...              ...  
420              no              no        0       no      unfurnished  
282              no             yes        0       no      unfurnished  
55               no             yes        1       no      unfurnished  
456              no              no        0      yes   semi-furnished  
200              no             yes        0       no   semi-furnished  

[436 rows x 12 columns]

In [45]:
x_test


area  bedrooms  bathrooms  stories mainroad guestroom basement  \
339  3180         4          2        2      yes        no       no   
62   6240         4          2        2      yes        no       no   
236  2870         2          1        2      yes       yes      yes   
454  4500         3          1        2      yes        no       no   
541  2400         3          1        1       no        no       no   
..    ...       ...        ...      ...      ...       ...      ...   
363  3584         2          1        1      yes        no       no   
521  3635         2          1        1       no        no       no   
79   6000         3          2        3      yes       yes       no   
502  3480         2          1        1      yes        no       no   
483  6615         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
339              no              no        0       no        furnished  
62               no             yes        1       no        furnished  
236              no              no        0      yes   semi-furnished  
454              no             yes        0       no      unfurnished  
541              no              no        0       no   semi-furnished  
..              ...             ...      ...      ...              ...  
363             yes              no        0       no   semi-furnished  
521              no              no        0       no      unfurnished  
79               no             yes        0       no        furnished  
502              no              no        1       no   semi-furnished  
483              no              no        0       no   semi-furnished  

[109 rows x 12 columns]

In [46]:
y_train

price
209  4900000
362  3710000
112  6083000
352  3780000
348  3815000
..       ...
420  3360000
282  4270000
55   7350000
456  3118850
200  4900000

[436 rows x 1 columns]

In [47]:
y_test

price
339  3885000
62   7070000
236  4620000
454  3143000
541  1767150
..       ...
363  3710000
521  2408000
79   6650000
502  2660000
483  2940000

[109 rows x 1 columns]

In [48]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer

In [81]:
tr = ColumnTransformer(transformers=[
    ('tn1',OneHotEncoder(drop = "first",sparse = False),["mainroad","guestroom","basement","hotwaterheating","airconditioning","prefarea"]),
    ('tn2',OrdinalEncoder(categories = [["furnished","semi-furnished","unfurnished"]]),["furnishingstatus"])
    #('tn3',StandardScaler(),["price"])
],remainder="passthrough")

In [82]:
tr

ColumnTransformer(remainder='passthrough',
                  transformers=[('tn1',
                                 OneHotEncoder(drop='first', sparse=False),
                                 ['mainroad', 'guestroom', 'basement',
                                  'hotwaterheating', 'airconditioning',
                                  'prefarea']),
                                ('tn2',
                                 OrdinalEncoder(categories=[['furnished',
                                                             'semi-furnished',
                                                             'unfurnished']]),
                                 ['furnishingstatus'])])

In [83]:
a = tr.fit_transform(x_train)

In [84]:
a

array([[1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 2., 2., 0.],
       ...,
       [1., 0., 0., ..., 1., 2., 1.],
       [1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 1., ..., 1., 2., 0.]])

In [85]:
b = tr.fit_transform(x_test)

In [86]:
b

array([[1., 0., 0., ..., 2., 2., 0.],
       [1., 0., 0., ..., 2., 2., 1.],
       [1., 1., 1., ..., 1., 2., 0.],
       ...,
       [1., 1., 0., ..., 2., 3., 0.],
       [1., 0., 0., ..., 1., 1., 1.],
       [1., 0., 0., ..., 1., 2., 0.]])

In [87]:
from sklearn.linear_model import LinearRegression

In [88]:
lr = LinearRegression()

In [89]:
lr.fit(a,y_train)

LinearRegression()

In [90]:
lr.predict(b)

array([[4832982.94463812],
       [6681508.86235136],
       [4372237.45511706],
       [4353456.09347481],
       [2302052.95828201],
       [6568824.60865779],
       [3465207.33441429],
       [3721888.71299639],
       [4180018.18794908],
       [5739945.02836522],
       [2050035.71250412],
       [7572565.82500301],
       [3652425.77910879],
       [2643555.48816921],
       [6376930.8392508 ],
       [2878033.01053205],
       [3170702.42380459],
       [4717488.57088926],
       [4419297.65396939],
       [4393905.78662883],
       [2618145.02340396],
       [5835554.95213759],
       [5672165.63839958],
       [5000838.96154279],
       [5221901.74132986],
       [3797840.92958373],
       [5987618.04596021],
       [2731239.42956149],
       [7738601.05798507],
       [6675144.73906612],
       [2768445.28928448],
       [6625504.74310031],
       [2911534.00021883],
       [3968744.41366951],
       [2277447.81419193],
       [3440851.56676943],
       [2579552.72922524],
 