In [ ]:
pandas series

In [4]:
import pandas as pd
s1 = pd.Series([1,2,3,4,5,6,7,8,9,100])
print(s1)               
               

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9    100
dtype: int64


In [29]:
import pandas as pd
s1 = pd.Series([1,2,3,4,5,6,7,8,9,100], dtype = float)               
print(s1)

0      1.0
1      2.0
2      3.0
3      4.0
4      5.0
5      6.0
6      7.0
7      8.0
8      9.0
9    100.0
dtype: float64


In [14]:
import pandas as pd
s1 = pd.Series([1,2,113,4,5,6,7,8,9,10],index = (["kl rahul","rohit sharma","virat kholi","surya","hardik","dinesh","ash","jp","yc","bk"]))
print(s1)

kl rahul          1
rohit sharma      2
virat kholi     113
surya             4
hardik            5
dinesh            6
ash               7
jp                8
yc                9
bk               10
dtype: int64


In [9]:
import pandas as pd
i = pd.Index(["kl rahul","rohit sharma","virat kholi","surya","hardik","dinesh","ash","jp","yc","bk"])
s1 = pd.Series([1,2,113,4,5,6,7,8,9,10],index = i)
print(s1)

kl rahul          1
rohit sharma      2
virat kholi     113
surya             4
hardik            5
dinesh            6
ash               7
jp                8
yc                9
bk               10
dtype: int64


In [1]:
import pandas as pd
s2 = pd.Series({"a":1,"b":2,"c":3,"d":4})
print(s2)

a    1
b    2
c    3
d    4
dtype: int64


In [3]:
import pandas as pd
marks1 = pd.Series([10,20,30,40], index = (["mehul","samy","nod","don"]), dtype = float)
print(marks1)

mehul    10.0
samy     20.0
nod      30.0
don      40.0
dtype: float64


In [7]:
import numpy as np
import pandas as pd
arr = np.arange(0,9).reshape(3,3)
print(arr)
df = pd.DataFrame(arr, index = ["a","b","c"] ,columns= ["A","B","C"])
print(df)
                                                        

[[0 1 2]
 [3 4 5]
 [6 7 8]]
   A  B  C
a  0  1  2
b  3  4  5
c  6  7  8


In [12]:
import numpy as np
import pandas as pd
arr = np.array([[12,13,14],[120,1500,100],[21,31,41]])
print(arr)
df = pd.DataFrame(arr, index = ["rahul","gururaj","gurunath"] ,columns= ["OSA","JAVA","PYTHON"])
print(df)
                 

[[  12   13   14]
 [ 120 1500  100]
 [  21   31   41]]
          OSA  JAVA  PYTHON
rahul      12    13      14
gururaj   120  1500     100
gurunath   21    31      41


In [13]:
import numpy as np
import pandas as pd
arr = np.array([[100,100,100],[99,99,99],[100,100,100]])
print(arr)
df  = pd.DataFrame(arr,index = ["gururaj","tanishk","gurunath"],columns = ["OSA","PYTHON","JAVA"])
print(df)

[[100 100 100]
 [ 99  99  99]
 [100 100 100]]
          OSA  PYTHON  JAVA
gururaj   100     100   100
tanishk    99      99    99
gurunath  100     100   100


In [17]:
import numpy as np
import pandas as pd
df = pd.DataFrame({"OSA":[20,30,40],"JAVA":[20,32,12,14]})
print(df)
                 

ValueError: All arrays must be of the same length

In [20]:
import numpy as np
import pandas as pd
df = pd.DataFrame({"OSA":[20,30,40],"JAVA":[20,32,12]})
print(df)

   OSA  JAVA
0   20    20
1   30    32
2   40    12


In [21]:
import numpy as np
import pandas as pd
df = pd.DataFrame({"OSA":[20,30,40],"JAVA":[20,32,12]},index = ["tanishk","gururaj","nihal"])
print(df)

         OSA  JAVA
tanishk   20    20
gururaj   30    32
nihal     40    12


In [25]:
import pandas as pd
d = pd.Series([12,3,4,56,78,90])
c = pd.Series([12,3,4,56,78])
df  = pd.DataFrame({"osa":d,"java":c})
print(df)

   osa  java
0   12  12.0
1    3   3.0
2    4   4.0
3   56  56.0
4   78  78.0
5   90   NaN


In [35]:
import pandas as pd
i = pd.Index = (["karnataka","maharashtra","delhi"])
population = pd.Series([6.71,7.1,8.1],i)
cap = pd.Series(["banglore","mumbai","delhi"],i)
df  = pd.DataFrame({"population":population,"cap":cap})
print(df)

             population       cap
karnataka          6.71  banglore
maharashtra        7.10    mumbai
delhi              8.10     delhi


In [37]:
import pandas as pd
import numpy as np
arr = np.array([[100,200,300,400],[110,210,310,410],[111,222,333,444]])
df = pd.DataFrame(arr ,index = ["tanishk","nihal","gurunath"] ,columns = ["OSA","python","dbms","java"])
print(df)

          OSA  python  dbms  java
tanishk   100     200   300   400
nihal     110     210   310   410
gurunath  111     222   333   444


In [39]:
import pandas as pd
import numpy as np
arr = np.array([["1.7","banglore"],["2.2","mumbai"],["3.3","gandhi nagar"]])
df = pd.DataFrame(arr ,index = ["karnataka","maharashtra","gujrat"],columns= ["population","capital"])
print(df)

            population       capital
karnataka          1.7      banglore
maharashtra        2.2        mumbai
gujrat             3.3  gandhi nagar


In [42]:
import pandas as pd
a = pd.Series(["banglore","mumbai","gandhi nagar"],index = ["karnataka","maharashtra","gujrat"])
b = pd.Series([1.2,2.2,3.3],index = ["karnataka","maharashtra","gujrat"])
df = pd.DataFrame({"population":b,"capital":a})
print(df)

             population       capital
karnataka           1.2      banglore
maharashtra         2.2        mumbai
gujrat              3.3  gandhi nagar


In [66]:
import pandas as pd
import numpy as np
i = pd.Index = (["karnataka","maharashtra","gujrat"])
a = pd.Series(["banglore","mumbai","gandhi nagar"],index = i,name = "capital")
b = pd.Series([1.1,2.2,3.3],index = i,name = "population")
df = pd.DataFrame([a,b]).T
print(df)

                  capital population
karnataka        banglore        1.1
maharashtra        mumbai        2.2
gujrat       gandhi nagar        3.3


In [69]:
import pandas as pd
import numpy as np
i = pd.Index = (["karnataka","maharashtra","gujrat"])
a = pd.Series(["banglore","mumbai","gandhi nagar"],index = i,name = "capital")
b = pd.Series(["1.1","2.2","3.3"],index = i,name = "population")
df = pd.DataFrame({"population":b,"capital":a})
print(df.append(pd.DataFrame({"population": pd.Series({"andrapradesh":'7.2'}),
                              "capital" : pd.Series({"andrapradesh":"op"})
                            })
               ))

             population       capital
karnataka           1.1      banglore
maharashtra         2.2        mumbai
gujrat              3.3  gandhi nagar
andrapradesh        7.2            op


C:\Users\CS-L2-PC08\AppData\Local\Temp\ipykernel_10532\1307183462.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df.append(pd.DataFrame({"population": pd.Series({"andrapradesh":'7.2'}),


In [3]:
import numpy as np
import pandas as pd
i = pd.Index = (["karnataka","maharashtra","gujrat"])
pop = pd.Series(["6.72","12.54","7.0"],index = i,name = "population")
cap = pd.Series(["banglore","mumbai","gandhi nagar"],index = i,name = "capital")
df = ({"population":pop,"capital":cap})
df1 = pd.concat([df,pd.DataFrame({
    "area":pd.Series(["2.1","3.1","5.5"],index = pop.index),
    "cm":pd.Series(["bomai","shinde","xyz"],index = pop.index)                          
                                })
                ],axis=1
               )
#df1.to_csv("cities_csv")
df1

TypeError: cannot concatenate object of type '<class 'dict'>'; only Series and DataFrame objs are valid

In [ ]:
import numpy as np 
import pandas as pd
i=pd.Index(['karnataka','mahrashtra','Gujarat'])
pop=pd.Series(['6.72','12.54','7.0'],index=i,name="population")
cap=pd.Series(['Bangalore','Mumbai','gandhinagar'],index=i,name="capital")
df=pd.DataFrame({"population":pop,"capital":cap})
print(df)
print("\n\n")
df1=pd.concat([df,pd.DataFrame({"  area":pd.Series(['2.1','3.1','5.5'],index=pop.index),"cm":pd.Series(['Bomai','Shinde','Patel'],index=pop.index)})],axis=1)
#df1.to_csv("cities.csv")
print(df1)

In [4]:
import numpy as np 
import pandas as pd
i=pd.Index(['karnataka','mahrashtra','Gujarat'])
pop=pd.Series(['6.72','12.54','7.0'],index=i,name="population")
cap=pd.Series(['Bangalore','Mumbai','gandhinagar'],index=i,name="capital")
df=pd.DataFrame({"population":pop,"capital":cap})
print(df)
print("\n\n")
df1=pd.concat([df,pd.DataFrame({"  area":pd.Series(['2.1','3.1','5.5'],index=pop.index),"cm":pd.Series(['Bomai','Shinde','Patel'],index=pop.index)})],axis=1)
#df1.to_csv("cities.csv")
print(df1)

TypeError: 'list' object is not callable

pandas subsetting

In [6]:
import pandas as pd 
import numpy as np
from pandas import Series,DataFrame

In [22]:
srs = Series([0,1,2,3,4],index = ["Alpha","Beta","Gama","Delta","Elipson"])
print(srs)

Alpha      0
Beta       1
Gama       2
Delta      3
Elipson    4
dtype: int64


In [23]:
srs[:2]

Alpha    0
Beta     1
dtype: int64

In [24]:
srs[["Beta","Delta"]]

Beta     1
Delta    3
dtype: int64

In [20]:
srs["Beta":"Delta"]

Beta     1
Gama     2
Delta    3
dtype: int64

In [25]:
print(srs)
srs[srs>3]

Alpha      0
Beta       1
Gama       2
Delta      3
Elipson    4
dtype: int64


Elipson    4
dtype: int64

In [26]:
srs >3

Alpha      False
Beta       False
Gama       False
Delta      False
Elipson     True
dtype: bool

In [27]:
a = Series(["zero","one","two","three","four"],index = [3,2,4,0,1])
print(a)

3     zero
2      one
4      two
0    three
1     four
dtype: object


In [28]:
a[2:4]

4      two
0    three
dtype: object

In [29]:
a.iloc[1:4]

2      one
4      two
0    three
dtype: object

In [30]:
a.loc[3:0]

3     zero
2      one
4      two
0    three
dtype: object

In [31]:
ab = DataFrame(np.arange(21).reshape(7,3),columns = ["AAA","BBB","CCC"],index = ["alpha","beta","gama","delta","elipson","zeta","eta"])
print(ab)

         AAA  BBB  CCC
alpha      0    1    2
beta       3    4    5
gama       6    7    8
delta      9   10   11
elipson   12   13   14
zeta      15   16   17
eta       18   19   20


In [32]:
ab.AAA

alpha       0
beta        3
gama        6
delta       9
elipson    12
zeta       15
eta        18
Name: AAA, dtype: int32

In [33]:
ab[["AAA","BBB"]]

AAA  BBB
alpha      0    1
beta       3    4
gama       6    7
delta      9   10
elipson   12   13
zeta      15   16
eta       18   19

In [37]:
ab.iloc[1:2:2]

AAA  BBB  CCC
beta    3    4    5

In [48]:
ab.iloc[:, 1:3]

BBB  CCC
alpha      1    2
beta       4    5
gama       7    8
delta     10   11
elipson   13   14
zeta      16   17
eta       19   20

In [39]:
ab.iloc[:, 1:3].loc[['alpha', 'gama', 'zeta']]

BBB  CCC
alpha    1    2
gama     7    8
zeta    16   17

In [40]:
df2 = ab.iloc[:, 1:3].loc[['alpha', 'gama', 'zeta']].copy()
df2

BBB  CCC
alpha    1    2
gama     7    8
zeta    16   17

In [41]:
df2['CCC'] = Series({'alpha':11, 'gama':18, 'zeta':5})
df2

BBB  CCC
alpha    1   11
gama     7   18
zeta    16    5

In [44]:
df2.iloc[2, 0] = 2
df2

BBB  CCC
alpha    1   11
gama     7    2
zeta     2    2