In [462]:
import pandas as pd
import numpy as np

In [463]:
df = pd.read_csv('dataset/Social_Network_Ads.csv')

In [464]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [465]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [466]:
df.fillna(method = 'bfill',inplace = True)

In [467]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [468]:
df.dropna(inplace = True)

In [469]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [470]:
df.drop(columns=['User ID'],inplace = True)

In [471]:
df

Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [472]:
x = pd.DataFrame(df.iloc[:,0:3])
x

Gender  Age  EstimatedSalary
0      Male   19            19000
1      Male   35            20000
2    Female   26            43000
3    Female   27            57000
4      Male   19            76000
..      ...  ...              ...
395  Female   46            41000
396    Male   51            23000
397  Female   50            20000
398    Male   36            33000
399  Female   49            36000

[400 rows x 3 columns]

In [473]:
y = df.iloc[:,-1]
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [474]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [475]:
tr = ColumnTransformer(transformers = [
    ('t1',OneHotEncoder(drop = 'first',sparse=False),['Gender'])
],remainder = "passthrough")

In [476]:
a = tr.fit_transform(df)

In [477]:
df = pd.DataFrame(a)

In [478]:
df

0     1        2    3
0    1.0  19.0  19000.0  0.0
1    1.0  35.0  20000.0  0.0
2    0.0  26.0  43000.0  0.0
3    0.0  27.0  57000.0  0.0
4    1.0  19.0  76000.0  0.0
..   ...   ...      ...  ...
395  0.0  46.0  41000.0  1.0
396  1.0  51.0  23000.0  1.0
397  0.0  50.0  20000.0  1.0
398  1.0  36.0  33000.0  0.0
399  0.0  49.0  36000.0  1.0

[400 rows x 4 columns]

In [479]:
x = pd.DataFrame(df.iloc[:,0:3])
x

0     1        2
0    1.0  19.0  19000.0
1    1.0  35.0  20000.0
2    0.0  26.0  43000.0
3    0.0  27.0  57000.0
4    1.0  19.0  76000.0
..   ...   ...      ...
395  0.0  46.0  41000.0
396  1.0  51.0  23000.0
397  0.0  50.0  20000.0
398  1.0  36.0  33000.0
399  0.0  49.0  36000.0

[400 rows x 3 columns]

In [480]:
y = df.iloc[:,-1]
y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
395    1.0
396    1.0
397    1.0
398    0.0
399    1.0
Name: 3, Length: 400, dtype: float64

In [481]:
from sklearn.model_selection import train_test_split

In [482]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = 2)

In [483]:
x_train

0     1         2
205  0.0  47.0   47000.0
354  1.0  36.0   99000.0
3    0.0  27.0   57000.0
264  1.0  48.0   90000.0
194  1.0  28.0   89000.0
..   ...   ...       ...
299  1.0  46.0  117000.0
22   1.0  48.0   41000.0
72   0.0  20.0   23000.0
15   1.0  29.0   80000.0
168  1.0  29.0  148000.0

[320 rows x 3 columns]

In [484]:
x_test

0     1         2
94   0.0  29.0   83000.0
32   0.0  21.0   16000.0
225  1.0  37.0   53000.0
157  1.0  29.0   75000.0
356  1.0  54.0   70000.0
..   ...   ...       ...
188  1.0  35.0   72000.0
223  1.0  60.0  102000.0
65   1.0  24.0   58000.0
262  0.0  55.0  125000.0
186  0.0  20.0   82000.0

[80 rows x 3 columns]

In [485]:
y_train

205    0.0
354    1.0
3      0.0
264    1.0
194    0.0
      ... 
299    1.0
22     1.0
72     0.0
15     0.0
168    1.0
Name: 3, Length: 320, dtype: float64

In [486]:
y_test

94     0.0
32     0.0
225    0.0
157    0.0
356    1.0
      ... 
188    0.0
223    1.0
65     0.0
262    1.0
186    0.0
Name: 3, Length: 80, dtype: float64

In [487]:
from sklearn.svm import SVC

In [488]:
s = SVC()

In [489]:
s.fit(x_train,y_train)

SVC()

In [490]:
y_pred = s.predict(x_test)

In [491]:
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [492]:
confusion_matrix(y_test,y_pred)


array([[46,  2],
       [20, 12]], dtype=int64)

In [493]:
accuracy_score(y_test,y_pred)

0.725

In [494]:
f1_score(y_test,y_pred)

0.5217391304347825

In [495]:
precision_score(y_test,y_pred)

0.8571428571428571

In [496]:
recall_score(y_test,y_pred)

0.375

In [497]:
df2 = pd.read_csv('dataset/titanic.csv')

In [498]:
df2

PassengerId  Survived  Pclass  \
0              1       0.0       3   
1              1       0.0       3   
2              1       0.0       3   
3              1       0.0       3   
4              2       NaN       1   
..           ...       ...     ...   
896          887       0.0       2   
897          888       1.0       1   
898          889       0.0       3   
899          890       1.0       1   
900          891       0.0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1                              Braund, Mr. Owen Harris    male  22.0      1   
2                              Braund, Mr. Owen Harris    male  22.0      1   
3                              Braund, Mr. Owen Harris    male  22.0      1   
4    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
..                                                 ...     ...   ...    ...   
896                              Montvila, Rev. Juozas    male  27.0      0   
897                       Graham, Miss. Margaret Edith  female  19.0      0   
898           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
899                              Behr, Mr. Karl Howell    male  26.0      0   
900                                Dooley, Mr. Patrick    male  32.0      0   

     Parch      Ticket     Fare Cabin Embarked  
0        0   A/5 21171   7.2500   NaN        S  
1        0   A/5 21171   7.2500   NaN        S  
2        0   A/5 21171   7.2500   NaN        S  
3        0   A/5 21171   7.2500   NaN        S  
4        0    PC 17599  71.2833   C85        C  
..     ...         ...      ...   ...      ...  
896      0      211536  13.0000   NaN        S  
897      0      112053  30.0000   B42        S  
898      2  W./C. 6607  23.4500   NaN        S  
899      0      111369  30.0000  C148        C  
900      0      370376   7.7500   NaN        Q  

[901 rows x 12 columns]

In [499]:
df2.isnull().sum()

PassengerId      0
Survived         4
Pclass           0
Name             0
Sex              0
Age            178
SibSp            0
Parch            0
Ticket           0
Fare             3
Cabin          690
Embarked         2
dtype: int64

In [500]:
df2.fillna(method = 'ffill',inplace = True)

In [501]:
df2.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          4
Embarked       0
dtype: int64

In [502]:
df2.dropna(inplace = True)

In [503]:
df2.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [504]:
df2.duplicated().sum()

7

In [505]:
df2.drop_duplicates(inplace = True)

In [506]:
df2.duplicated().sum()

0

In [507]:
df2.drop(columns = ['PassengerId','Name','Ticket','Fare','Cabin'],inplace = True)

In [508]:
df2

Survived  Pclass     Sex   Age  SibSp  Parch Embarked
4         0.0       1  female  38.0      1      0        C
5         0.0       3  female  38.0      0      0        S
6         0.0       1  female  35.0      1      0        S
7         0.0       3    male  35.0      0      0        S
8         0.0       3    male  35.0      0      0        Q
..        ...     ...     ...   ...    ...    ...      ...
896       0.0       2    male  27.0      0      0        S
897       1.0       1  female  19.0      0      0        S
898       0.0       3  female  19.0      1      2        S
899       1.0       1    male  26.0      0      0        C
900       0.0       3    male  32.0      0      0        Q

[890 rows x 7 columns]

In [509]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [510]:
tr = ColumnTransformer(transformers = [
    ('t1',OneHotEncoder(drop = 'first',sparse = False),['Sex','Embarked'])
],remainder="passthrough")

In [511]:
a = tr.fit_transform(df2)

In [512]:
df1 = pd.DataFrame(a)
df1

0    1    2    3    4     5    6    7
0    0.0  0.0  0.0  0.0  1.0  38.0  1.0  0.0
1    0.0  0.0  1.0  0.0  3.0  38.0  0.0  0.0
2    0.0  0.0  1.0  0.0  1.0  35.0  1.0  0.0
3    1.0  0.0  1.0  0.0  3.0  35.0  0.0  0.0
4    1.0  1.0  0.0  0.0  3.0  35.0  0.0  0.0
..   ...  ...  ...  ...  ...   ...  ...  ...
885  1.0  0.0  1.0  0.0  2.0  27.0  0.0  0.0
886  0.0  0.0  1.0  1.0  1.0  19.0  0.0  0.0
887  0.0  0.0  1.0  0.0  3.0  19.0  1.0  2.0
888  1.0  0.0  0.0  1.0  1.0  26.0  0.0  0.0
889  1.0  1.0  0.0  0.0  3.0  32.0  0.0  0.0

[890 rows x 8 columns]

In [513]:
x = pd.DataFrame(df.iloc[:,1:])

In [514]:
x

1        2    3
0    19.0  19000.0  0.0
1    35.0  20000.0  0.0
2    26.0  43000.0  0.0
3    27.0  57000.0  0.0
4    19.0  76000.0  0.0
..    ...      ...  ...
395  46.0  41000.0  1.0
396  51.0  23000.0  1.0
397  50.0  20000.0  1.0
398  36.0  33000.0  0.0
399  49.0  36000.0  1.0

[400 rows x 3 columns]

In [515]:
y = df.iloc[:,0]

In [516]:
y

0      1.0
1      1.0
2      0.0
3      0.0
4      1.0
      ... 
395    0.0
396    1.0
397    0.0
398    1.0
399    0.0
Name: 0, Length: 400, dtype: float64

In [517]:
from sklearn.model_selection import train_test_split

In [518]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 2)

In [519]:
x_train

1         2    3
205  47.0   47000.0  0.0
354  36.0   99000.0  1.0
3    27.0   57000.0  0.0
264  48.0   90000.0  1.0
194  28.0   89000.0  0.0
..    ...       ...  ...
299  46.0  117000.0  1.0
22   48.0   41000.0  1.0
72   20.0   23000.0  0.0
15   29.0   80000.0  0.0
168  29.0  148000.0  1.0

[320 rows x 3 columns]

In [520]:
x_test

1         2    3
94   29.0   83000.0  0.0
32   21.0   16000.0  0.0
225  37.0   53000.0  0.0
157  29.0   75000.0  0.0
356  54.0   70000.0  1.0
..    ...       ...  ...
188  35.0   72000.0  0.0
223  60.0  102000.0  1.0
65   24.0   58000.0  0.0
262  55.0  125000.0  1.0
186  20.0   82000.0  0.0

[80 rows x 3 columns]

In [521]:
y_train

205    0.0
354    1.0
3      0.0
264    1.0
194    1.0
      ... 
299    1.0
22     1.0
72     0.0
15     1.0
168    1.0
Name: 0, Length: 320, dtype: float64

In [522]:
y_test

94     0.0
32     0.0
225    1.0
157    1.0
356    1.0
      ... 
188    1.0
223    1.0
65     1.0
262    0.0
186    0.0
Name: 0, Length: 80, dtype: float64

In [533]:
from sklearn.svm import SVC

In [534]:
s = SVC()

In [535]:
s.fit(x_train,y_train)

SVC()

In [536]:
y_pred = s.predict(x_test)

In [537]:
y_pred

array([1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1.,
       0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1.,
       0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1.,
       1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1.])

In [538]:
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [539]:
confusion_matrix(y_test,y_pred)

array([[19, 21],
       [19, 21]], dtype=int64)

In [540]:
accuracy_score(y_test,y_pred)

0.5

In [541]:
f1_score(y_test,y_pred)

0.5121951219512195