# Import mysql connector

In [7]:
import mysql.connector as con

# connection to database

In [9]:
import mysql.connector as con
new_db = con.connect(
    host = "localhost",
    user = "root",
    password = "root"
)
print(new_db)

# creating a database

In [10]:
import mysql.connector as con
new_db = con.connect(
    host = "localhost",
    user = "root",
    password = "root")
new_cur = new_db.cursor()
new_cur.execute("CREATE DATABASE college")

# check if database exist

In [11]:
import mysql.connector as con
new_db = con.connect(
    host = "localhost",
    user = "root",
    password = "root")
new_cur = new_db.cursor()
new_cur.execute("SHOW DATABASES")
for i in new_cur:
    print(i)

('college',)
('information_schema',)
('mysql',)
('performance_schema',)
('sakila',)
('sys',)
('world',)


# showing tables from database

In [18]:
import mysql.connector as con
new_db = con.connect(
    host = "localhost",
    user = "root",
    password = "root",
    database = "college")
new_cur = new_db.cursor()
new_cur.execute("SHOW TABLES")
for i in new_cur:
    print(i)

('student',)
('student1',)


# creating tables

In [15]:
import mysql.connector as con
new_db = con.connect(
    host = "localhost",
    user = "root",
    password = "root",
    database = "college")
new_cur = new_db.cursor()
new_cur.execute("CREATE TABLE student1(name varchar(900),regno varchar(10))")


# inserting into tables

In [20]:
import mysql.connector as con
new_db = con.connect(
    host = "localhost",
    user = "root",
    password = "root",
    database = "college")
new_cur = new_db.cursor()
query = "INSERT INTO student1(name,regno) values(%s,%s)"
values = "tanishk","393cs20029"
new_cur.execute(query,values)
new_db.commit()
print(new_cur.rowcount,"new record inserted")


1 new record inserted


# inserting multiple values into table

In [29]:
import mysql.connector as con
new_db = con.connect(
    host = "localhost",
    user = "root",
    password = "root",
    database = "college")
new_cur = new_db.cursor()
query = "INSERT INTO student1(name,regno) values(%s,%s)"
values = [("abhishek","393cs19002"),
          ("rahul","393cs20012"),
          ("prajwal","393cs20013"),
          ("gururaj","393cs21702")
         ]
new_cur.executemany(query,values)
new_db.commit()
print(new_cur.rowcount,"new record inserted")


4 new record inserted


In [32]:
import mysql.connector as con
new_db = con.connect(
    host = "localhost",
    user = "root",
    password = "root",
    database = "college")
new_cur = new_db.cursor()
new_cur.execute("SELECT * FROM student1")
for i in new_cur:
    print(i)

('tanishk', '393cs20029')
('abhishek', '393cs19002')
('rahul', '393cs20012')
('prajwal', '393cs20013')
('gururaj', '393cs21702')


In [ ]:
import mysql.connector as con
new_db = con.connect(
    host = "localhost",
    user = "root",
    password = "root",
    database = "college")
new_cur = new_db.cursor()
new_cur.execute("SELECT name FROM student1")
for i in new_cur:
    print(i)

In [1]:
import mysql.connector as con
new_db = con.connect(
    host = "localhost",
    user = "root",
    password = "root",
    database = "college")
new_cur = new_db.cursor()
new_cur.execute("SELECT name FROM student1")
for i in new_cur:
    print(i)

('tanishk',)
('abhishek',)
('rahul',)
('prajwal',)
('gururaj',)


In [1]:
import mysql.connector as con
new_db = con.connect(
    host = "localhost",
    user = "root",
    password = "root",
    database = "college")
new_cur = new_db.cursor()
new_cur.execute("SELECT * FROM student1")
for i in new_cur:
    print(i)

('tanishk', '393cs20029')
('abhishek', '393cs19002')
('rahul', '393cs20012')
('prajwal', '393cs20013')
('gururaj', '393cs21702')


In [29]:
import numpy as np
arr = np.array([[3,2,5],
               [3,2,5],
               [3,2,5]])
print(arr)
print(arr.dtype)
print(arr.shape)

[[3 2 5]
 [3 2 5]
 [3 2 5]]
int32
(3, 3)


In [29]:
import numpy as np
arr = np.array([[3,2,5],
               [3,2,5],
               [3,2,5]])
print(arr)
print(arr.dtype)
print(arr.shape)

[[3 2 5]
 [3 2 5]
 [3 2 5]]
int32
(3, 3)


In [30]:
import numpy as np
arr = np.array([3,2,5])
print(arr)
print(arr.dtype)
print(arr.shape)

[3 2 5]
int32
(3,)


# example of rand

In [7]:
import numpy as np
arr = np.random.rand(3,2,5)
print(arr)
print(arr.dtype)
print(arr.shape)

[[[0.60250551 0.39361733 0.13344856 0.82398468 0.02626658]
  [0.12930312 0.80224919 0.38259547 0.03919851 0.60816936]]

 [[0.65293375 0.42953539 0.2967605  0.59025042 0.05627163]
  [0.21862698 0.60018878 0.39434875 0.97866772 0.07124361]]

 [[0.7989858  0.08352609 0.82541146 0.2566444  0.44906697]
  [0.24657831 0.91384536 0.99051004 0.84553879 0.66775806]]]
float64
(3, 2, 5)


In [6]:
import numpy as np
arr = np.random.randn(3,2,2)
print(arr)
print(arr.dtype)
print(arr.shape)

[[[ 0.88448269 -0.69114051]
  [-0.27382475  0.79640643]]

 [[ 0.28218511  0.79692685]
  [ 0.09735775  1.02838432]]

 [[ 0.84229529 -0.12316504]
  [-2.02998994 -0.45162206]]]
float64
(3, 2, 2)


In [26]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr[0,2])
print(arr[1,3])
print(arr[-2,-3])
print(arr[-1,-2])
print(arr[0,-3])
print(arr[1,-2])
print(arr[-2,2])
print(arr[-1,3])


3
9
3
9
3
9
3
9


In [ ]:
# import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr[0]+arr[1])

# slice elements from index 1 to index 5 from the following array

In [45]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
print(a[1:5])

[2 3 4 5]


# slice elements from index 4 to the end of the array

In [44]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
print(a[4:])

[5 6 7]


# slice elements from beginning index 4(n0t included)

In [43]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
print(a[:4])

[1 2 3 4]


# negative slicing
slice from index 3 from the end to index 1 from the end:

In [42]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
print(a[-3:-1])

[5 6]


#return every other element from index 1 to index 5

In [46]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
print(a[1:5:2])

[2 4]


return every other element from entire array

In [48]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
print(a[::2])

[1 3 5 7]


# slicing 2d array

from the second element,slice the element from index 1 to index 4(not included)

In [52]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(a[1,1:4])

[7 8 9]


from both arrays, return index 2:

In [53]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(a[0:2,2])

[3 8]


from both elements, slic eindex 1 to index 4(not included), this will return a 2d array

In [58]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(a[0:2,1:4])

[[2 3 4]
 [7 8 9]]


array copy :in this copy dosent effect real one if any changes happend

In [4]:
import numpy as np
a=np.array([1,2,3,4])
b=np.copy(a)
print(a)
b[0]=20
print(b)

[1 2 3 4]
[20  2  3  4]


array view : view effect real one if any changes happend

In [11]:
import numpy as np
a=np.array([1,2,3,4,5])
b=a.view()
a[2]=8
print(a)
print(b)


[1 2 8 4 5]
[1 2 8 4 5]


array reshaping : by using this function we can shape the give array 

In [13]:
import numpy as np
a=np.array([1,2,3,4])
b=a.reshape(2,2)
print(a)
print(b)

[1 2 3 4]
[[1 2]
 [3 4]]


In [14]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,0])
b=a.reshape(5,2)
print(a)
print(b)

[1 2 3 4 5 6 7 8 9 0]
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]


In [15]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape(3,2,2)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


array sum :by using this function we can add array 

In [17]:
import numpy as np
a=np.array([1,2,3,4])
b=np.sum(a)
print(a)
print(b)

[1 2 3 4]
10


In [22]:
import numpy as np
a=np.array([[1,2,3,4],
           [1,2,3,4]])
b=np.sum(a, axis = 0)
print(a)
print(b)

[[1 2 3 4]
 [1 2 3 4]]
[2 4 6 8]


mean 

In [26]:
import numpy as np
a=np.array([1,2,3,4])
b=np.mean(a)
print(a)
print(b)

[1 2 3 4]
2.5


In [30]:
import numpy as np
a=np.array([[1,2,3,4],
            [8,2,3,4]])
b=np.mean(a , axis = 1)
print(a)
print(b)

[[1 2 3 4]
 [8 2 3 4]]
[2.5  4.25]


std

In [32]:
import numpy as np
a=np.array([[1,2,3,4],
            [8,2,3,4]])
b=np.mean(a , axis = 0)
print(a)
print(b)

[[1 2 3 4]
 [8 2 3 4]]
[4.5 2.  3.  4. ]


In [31]:
import numpy as np
a=np.array([[1,2,3,4],
            [8,2,3,4]])
b=np.std(a , axis = 1)
print(a)
print(b)

[[1 2 3 4]
 [8 2 3 4]]
[1.11803399 2.27760839]


In [33]:
import numpy as np
a=np.array([[1,2,3,4],
            [8,2,3,4]])
b=np.std(a , axis = 0)
print(a)
print(b)

[[1 2 3 4]
 [8 2 3 4]]
[3.5 0.  0.  0. ]


array var

In [34]:
import numpy as np
a=np.array([[1,2,3,4],
            [8,2,3,4]])
b=np.var(a , axis = 1)
print(a)
print(b)

[[1 2 3 4]
 [8 2 3 4]]
[1.25   5.1875]


In [35]:
import numpy as np
a=np.array([[1,2,3,4],
            [8,2,3,4]])
b=np.var(a , axis = 0)
print(a)
print(b)

[[1 2 3 4]
 [8 2 3 4]]
[12.25  0.    0.    0.  ]


array min

In [36]:
import numpy as np
a=np.array([[1,2,3,4],
            [8,2,3,4]])
b=np.min(a , axis = 1)
print(a)
print(b)

[[1 2 3 4]
 [8 2 3 4]]
[1 2]


In [39]:
import numpy as np
a=np.array([[1,2,3,4],
            [8,2,3,4]])
b=np.min(a , axis = 0)
print(a)
print(b)

[[1 2 3 4]
 [8 2 3 4]]
[1 2 3 4]


array max

In [37]:
import numpy as np
a=np.array([[1,2,3,4],
            [8,2,3,4]])
b=np.max(a , axis = 1)
print(a)
print(b)

[[1 2 3 4]
 [8 2 3 4]]
[4 8]


In [40]:
import numpy as np
a=np.array([[1,2,3,4],
            [8,2,3,4]])
b=np.max(a , axis = 0)
print(a)
print(b)

[[1 2 3 4]
 [8 2 3 4]]
[8 2 3 4]
